Disable rustc 1.31.{0, 1}
Because of some weird error:

    error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
      --> src/main.rs:29:5
       |
    17 | mod config;
       | ----------- not an extern crate passed with `--extern`
    ...
    29 | use config::Configuration;
       |     ^^^^^^
       |
    note: this import refers to the module defined here
      --> src/main.rs:17:1
       |
    17 | mod config;
       | ^^^^^^^^^^^

    error: aborting due to previous error

This has nothing to do with the "mod config". The compiler tells us
something about missing featureflags or so, which is not relevant here...

Strange. Just disable the 1.31 versions.